services:
  - type: web
    name: content-gen-ai-server
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn run:app --host 0.0.0.0 --port $PORT